### ISSUE TITLE
Issue displaying panel: jsxDEV export not provided

### ISSUE THREAD

**Issue by davidkpiano** [jacksteamdev/crx-react-devtools#1]
First of all, thanks so much for setting this up!

When I try this out, I see the **React Counter** panel, but it is a blank white screen. Inspecting it, I see this error:

```
panel?t=1649732673075:18 SyntaxError: The requested module '/node_modules/.vite/deps/react_jsx-dev-runtime.js?v=78a6cc56'
does not provide an export named 'jsxDEV'
```

Is this an issue on my end?

**Comment by jacksteamdev** [comment]
@davidkpiano Thanks for trying it out! Unfortunately, I wasn't able to reproduce this error by cloning the repo. 😬

Based on previous experience, I'd say this is a problem with Vite dependency pre-bundling. Restarting `vite dev` usually clears it up. You might need to reinstall the extension in the browser. LMK if it still doesn't work.

**Comment by jacksteamdev** [comment]
I just pushed a couple of tweaks to this boilerplate that might help
